version: "1.0"
services:
  mongodb-docker:
    image: mongo:latest
    container_name: "mongodb-docker"
    ports:
      - 27017:27017
  springboot-mongodb:
    image: springboot-mongodb:latest
    container_name: springboot-mongodb
    ports:
      - 8080:8080
    links:
      - mongodb-docker
